[package]
name = "labrinth"
version = "0.2.0"
#Team members, please add your emails and usernames
authors = ["geometrically <jai.a@tuta.io>", "Redblueflame <contact@redblueflame.com>", "Aeledfyr <aeledfyr@gmail.com>", "Charalampos Fanoulis <yo@fanoulis.dev>", "AppleTheGolden <scotsbox@protonmail.com>"]
edition = "2018"
license = "AGPL-3.0"

[[bin]]
name = "labrinth"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-web = "4.0.0"
actix-rt = "2.6.0"
tokio-stream = "0.1.8"
actix-multipart = "0.4.0"
actix-cors = "0.6.0"

meilisearch-sdk = "0.15.0"
reqwest = { version = "0.11.9", features = ["json"] }

yaserde = "0.6.0"
yaserde_derive = "0.6.0"
xml-rs = "0.8.3"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5.1"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7.3"
base64 = "0.13.0"
sha1 = { version = "0.6.0", features = ["std"] }
sha2 = "0.9.2"
bitflags = "1.2.1"
zip = "0.5.12"
itertools = "0.10.3"

validator = { version = "0.13", features = ["derive"] }
regex = "1.5.4"
url = "2.2.2"
urlencoding = "2.1.0"

gumdrop = "0.8.0"
dotenv = "0.15"
log = "0.4.8"
env_logger = "0.8.1"
thiserror = "1.0.21"
lazy_static = "1.4.0"

futures = "0.3.6"
futures-timer = "3.0.2"
rust-s3 = "0.29.0"
async-trait = "0.1.41"

sqlx = { version = "0.5.10", features = ["runtime-actix-rustls", "postgres", "chrono", "offline", "macros", "migrate"] }

bytes = "1.1.0"

dashmap = "4.0.2"
hex = "0.4.3"
