name: Custom Build and Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_rust_tests:
    name: Run rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
          cat lcov.info
        env:
          SQLX_OFFLINE: true # needed to keep it from trying to connect to a database

