name: Custom Build and Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  custom-build-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Entire Workspace
        run: cargo build --workspace --all-features
        env:
          SQLX_OFFLINE: true
          DATABASE_URL: postgresql://labrinth:labrinth@localhost/postgres

      - name: Install llvm-tools and cargo-llvm-cov
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Generate Coverage for Main Crate Only
        run: cargo llvm-cov --package labrinth --all-features --codecov --output-path codecov.json
        env:
          SQLX_OFFLINE: true
          DATABASE_URL: postgresql://labrinth:labrinth@localhost/postgres
