name: Coverage2

on: [pull_request, push]

jobs:
  coverage2:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d

      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      # Cache dependencies and build artifacts
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: sqlx-cli
      - uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          SQLX_VERSION: 0.6.0
          SQLX_OFFLINE: true
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --no-clean --all-features --frozen --lcov --output-path lcov.info
        env:
          SQLX_VERSION: 0.6.0
          SQLX_OFFLINE: true
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
