name: citarp

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  citarp:
    runs-on:                    ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d
      - name:                   Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error:     true
