name: Rust33

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Start containers
        run: docker compose up -d
      - name: Install self signed certificate
        run: |
          until [ -f ./resources/test/certs/cert.pem ]; do sleep 1; done
          sudo cp ./resources/test/certs/cert.pem /usr/local/share/ca-certificates/localhost.crt && sudo update-ca-certificates
        timeout-minutes: 1
      - name: Run integration tests
        run: cargo llvm-cov test --verbose --test '*'  --lcov --output-path lcov.integration-tests.info
        env:
          RUSTFLAGS: "-C instrument-coverage"
          SQLX_OFFLINE: "true"

      - name: Stop containers
        if: always()
        run: docker compose down
